title: Gary's Understandings
description: Gary's Understandings
author: Gary Huang
github: https://github.com/garyhuang123
about: A guy focuses on container ecosystem research & development, devops, data analysis, distributed system design.
disqus_shortname: gary_understands
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-github
      link: "https://github.com/garyhuang123"

urls:
    - text: About Me
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://garyhuang123.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
